// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxvzaxceulwxwpfnoaye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dnpheGNldWx3eHdwZm5vYXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjYwODUsImV4cCI6MjA1OTg0MjA4NX0.PEkjVtfilrMf2jhvlWXK05BMTgJXDS_FnvMQOT_wCQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);